/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.ed.gui;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author herlan
 */
public class TrappedMouse extends javax.swing.JFrame {

    private JLabel[] lab;
    private final char exitMarker = 'e', entryMarker = 'm', visited = '.';
    private final char passage = '0', wall = '1';

    int tam = 0;

    /**
     * Creates new form TrappedMouse
     *
     * @param rows
     * @param cols
     */
    public TrappedMouse(int rows, int cols) {
        initComponents();
        GridLayout grid = new GridLayout(rows, cols);
        tam = rows * cols;
        lab = new JLabel[tam];
        PainelLabirinto.setLayout(grid);

        for (int i = 0; i < tam; i++) {
            lab[i] = new JLabel();
        }
    }

    public void mountMaze(String maze) {
        char[] mazeCharArray = maze.toCharArray();

        for (int i = 0; i < tam; i++) {
            Character mazePoint = mazeCharArray[i];
            lab[i].setText(mazePoint.toString());
            PainelLabirinto.add(lab[i]);
        }

        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(TrappedMouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelFundo = new javax.swing.JPanel();
        PainelLabirinto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelFundo.setBackground(java.awt.Color.white);

        PainelLabirinto.setBackground(java.awt.Color.white);
        PainelLabirinto.setLayout(new java.awt.GridLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setText("Trapped Mouse");

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGroup(PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(PainelFundoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(PainelLabirinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(PainelLabirinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        getContentPane().add(PainelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 520, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JPanel PainelLabirinto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
