/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifrn.ed.gui;

import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author herlan
 */
public class TrappedMouse extends javax.swing.JFrame {

    private JLabel[] lab;
    private final char exitMarker = 'e', entryMarker = 'm', visited = '.';
    private final char passage = '0', wall = '1';
    private String sWall = "/br/com/ifrn/ed/gui/Wall.png";
    private String sPassage = "/br/com/ifrn/ed/gui/Passage.png";
    private String sCheese = "/br/com/ifrn/ed/gui/Cheese.png";
    private String sVisited = "/br/com/ifrn/ed/gui/Visited.png";
    private String sEntry = "/br/com/ifrn/ed/gui/House.png";
    private String sMouse = "/br/com/ifrn/ed/gui/Mouse.png";
    private ImageIcon iconWall, iconPassage, iconCheese, iconVisited, IconEntry, iconMouse;
    int tam = 0;

    /**
     * Creates new form TrappedMouse
     *
     * @param rows
     * @param cols
     */
    public TrappedMouse(int rows, int cols) {
        initComponents();
        GridLayout grid = new GridLayout(rows, cols);
        tam = rows * cols;
        lab = new JLabel[tam];
        PainelLabirinto.setLayout(grid);

        IconEntry = new ImageIcon(sEntry);
        iconCheese = new ImageIcon(sCheese);
        iconMouse = new ImageIcon(sMouse);
        iconPassage = new ImageIcon(sPassage);
        iconVisited = new ImageIcon(sVisited);
        iconWall = new ImageIcon(sWall);

        for (int i = 0; i < tam; i++) {
            lab[i] = new JLabel();
            PainelLabirinto.add(lab[i]);
        }
    }

    public void mountMaze(String maze) {
        char[] mazeCharArray = maze.toCharArray();        
        for (int i = 0; i < tam; i++) {
            Character mazePoint = mazeCharArray[i];

            switch (mazePoint) {
                case wall:
                    lab[i].setIcon(iconWall);
                    break;
                case visited:
                    lab[i].setIcon(iconVisited);
                    break;
                case passage:
                    lab[i].setIcon(iconPassage);
                    break;
                case entryMarker:
                    lab[i].setIcon(IconEntry);
                    break;
                case exitMarker:
                    lab[i].setIcon(iconCheese);
                    break;
            }
            //lab[i].setText(null);
        }

        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(TrappedMouse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PainelFundo = new javax.swing.JPanel();
        PainelLabirinto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PainelFundo.setBackground(java.awt.Color.white);

        PainelLabirinto.setBackground(java.awt.Color.white);
        PainelLabirinto.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setText("Trapped Mouse");

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(PainelLabirinto, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelFundoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PainelLabirinto, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(PainelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 520, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JPanel PainelLabirinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
